export { PraticaForm }           from './PraticaForm'
export { PraticaModal }          from './PraticaModal'
export { PraticaDettaglio }      from './PraticaDettaglio'
export { PraticaRow }            from './PraticaRow'
export { AvanzaFaseModal }       from './AvanzaFaseModal'
export { BloccoDocumentiAlert }  from './BloccoDocumentiAlert'
export { StatoPraticaBanner }    from './StatoPraticaBanner'
